In [ ]:
import numpy as np
import tensorflow as tf

## 캐릭터 1개만 사용

In [ ]:
x_data = np.array([[[1,0,0,0]]], dtype=np.float32)

hidden_size = 2
cell = tf.keras.layers.SimpleRNNCell(units=hidden_size)
rnn = tf.keras.layers.RNN(cell, return_sequences=True, return_state=True)
outputs, _states = rnn(x_data)

print(f"x_data: {x_data}, shape: {x_data.shape}")
print(f"outputs: {outputs}, shape: {outputs.shape}")    # 전체 시퀀스에 해당하는 스테이트값
print(f"states: {_states}, shape: {_states.shape}")       # 시퀀스의 마지막 스테이트값

x_data: [[[1. 0. 0. 0.]]], shape: (1, 1, 4)
outputs: [[[-0.6923366   0.23685794]]], shape: (1, 1, 2)
states: [[-0.6923366   0.23685794]], shape: (1, 2)


## 시퀀스 데이터 사용

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.utils import to_categorical

text = ['h','e','l','o']
tokenizer = Tokenizer()
tokenizer.fit_on_texts([text])
print('단어 집합 :',tokenizer.word_index)
x_data = to_categorical([0,1,2,2,3]).reshape(1,5,4)

단어 집합 : {'h': 1, 'e': 2, 'l': 3, 'o': 4}


In [ ]:
hidden_size = 2
rnn = tf.keras.layers.SimpleRNN(units=hidden_size, return_sequences=True, return_state=True)
outputs, states = rnn(x_data)

In [ ]:
print(f"x_data: {x_data}, shape: {x_data.shape}\n")
print(f"outputs: {outputs}, shape: {outputs.shape}\n")
print(f"states: {states}, shape: {states.shape}") 

x_data: [[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]], shape: (1, 5, 4)

outputs: [[[ 0.27707547  0.5824307 ]
  [ 0.29970938  0.7375634 ]
  [ 0.86382765  0.06893125]
  [ 0.810013   -0.656597  ]
  [-0.08628567 -0.8787988 ]]], shape: (1, 5, 2)

states: [[-0.08628567 -0.8787988 ]], shape: (1, 2)


## Batching input

In [ ]:
x_data = to_categorical([[0,1,2,2,3],[1,3,2,2,2],[2,2,1,1,2]]).reshape(3,5,4)

In [ ]:
hidden_size = 2
rnn = tf.keras.layers.SimpleRNN(units=hidden_size, return_sequences=True, return_state=True)
outputs, states = rnn(x_data)

In [ ]:
print(f"x_data: {x_data}, shape: {x_data.shape}\n")
print(f"outputs: {outputs}, shape: {outputs.shape}\n")
print(f"states: {states}, shape: {states.shape}") 

x_data: [[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]

 [[0. 1. 0. 0.]
  [0. 0. 0. 1.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]]

 [[0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]]], shape: (3, 5, 4)

outputs: [[[ 0.6486854   0.07767566]
  [-0.6219262  -0.04636822]
  [ 0.32624662 -0.01618274]
  [ 0.562509   -0.7244079 ]
  [ 0.3740215  -0.274199  ]]

 [[-0.7559136   0.5032242 ]
  [ 0.83254355  0.8695113 ]
  [ 0.92597866 -0.81813693]
  [ 0.03755745 -0.93779296]
  [-0.31775504 -0.7169879 ]]

 [[ 0.5075927  -0.53663623]
  [ 0.18663648 -0.84499073]
  [-0.94068503  0.13416566]
  [-0.80921817  0.9040075 ]
  [ 0.832691    0.40779996]]], shape: (3, 5, 2)

states: [[ 0.3740215  -0.274199  ]
 [-0.31775504 -0.7169879 ]
 [ 0.832691    0.40779996]], shape: (3, 2)


# ML lab12-2: RNN - Hi Hello Training

In [23]:
import numpy as np
import tensorflow as tf
from tensorflow import keras

idx2char = ['h', 'i', 'e', 'l', 'o']
y_data = [[1, 0, 2, 3, 3, 4]]  # ihello

hidden_size = 5 
input_dim = 5  # 캐릭터의 수가 5개다. 
sequence_length = 6  # 입력하는 단어 hihell가 6개이기 때문|ihello| == 6 
batch_size = 1
learning_rate = 0.1

x_one_hot = np.array([[[1, 0, 0, 0, 0],    # h 0
                       [0, 1, 0, 0, 0],    # i 1
                       [1, 0, 0, 0, 0],    # h 0
                       [0, 0, 1, 0, 0],    # e 2
                       [0, 0, 0, 1, 0],    # l 3
                       [0, 0, 0, 1, 0]]],  # l 3
                     dtype=np.float32)

y_one_hot = keras.utils.to_categorical(y_data, num_classes=hidden_size)

In [24]:
model = keras.Sequential()

 # 유닛은 5다. (원핫인코딩한 벡터로 출력하기 때문), 인풋 shape은 먼저 총 입력할 데이터수 (6)개, 그리고 각 데이터의 차원 (5개의 원핫인코딩 벡터)
cell = keras.layers.LSTMCell(units=hidden_size, input_shape=(sequence_length, input_dim))  
model.add(keras.layers.RNN(cell=cell, return_sequences=True))
model.add(keras.layers.TimeDistributed(keras.layers.Dense(units=hidden_size, activation='softmax')))

model.compile(loss='categorical_crossentropy', 
              optimizer=keras.optimizers.Adam(learning_rate=learning_rate), 
              metrics=['accuracy'])

In [ ]:
model.fit(x_one_hot, y_one_hot, epochs=50, batch_size=batch_size)
model.summary()

In [30]:
predictions = model.predict(x_one_hot)
for i, prediction in enumerate(predictions):
    print(prediction)
    result_str = [idx2char[c] for c in np.argmax(prediction, axis=1)]
    print('\nPrediction:', np.argmax(prediction, axis=1))
    print("Prediction str:", ''.join(result_str))

[[1.4485123e-06 9.9837863e-01 1.6133164e-03 4.5992074e-06 2.0055959e-06]
 [9.9907804e-01 2.4513693e-05 7.2397472e-04 2.7812268e-05 1.4559973e-04]
 [3.3646746e-05 1.2272120e-03 9.9817896e-01 5.6004641e-04 1.3039200e-07]
 [1.2675821e-05 4.5735879e-07 1.6818113e-04 9.9975759e-01 6.1179722e-05]
 [4.1050291e-05 1.6516027e-06 3.3960913e-04 9.9820113e-01 1.4165674e-03]
 [2.8758252e-05 7.8152261e-06 5.0441787e-07 2.5401842e-03 9.9742270e-01]]

Prediction: [1 0 2 3 3 4]
Prediction str: ihello


# ML lab12-3: Long Sequence RNN


In [47]:
import numpy as np
import tensorflow as tf
from tensorflow import keras

In [48]:
sample = 'if you want you'

idx2char = list(set(sample))    # 인덱스를 넣으면 캐릭터를 뱉는다.
# idx2char : ['y', 'u', 'a', 'n', 'w', 'i', 't', 'o', 'f', ' ']

char2idx = {c: i for i,c in enumerate(idx2char)}    # 캐릭터를 넣으면 인덱스를 뱉는다.
# char2idx : {' ': 9, 'a': 2, 'f': 8, 'i': 5, 'n': 3, 'o': 7, 't': 6, 'u': 1, 'w': 4, 'y': 0} 

sample_idx = [char2idx[c] for c in sample]  # 샘플을 인덱스로 변경
# sample_idx [5, 8, 9, 0, 7, 1, 9, 4, 2, 3, 6, 9, 0, 7, 1]

x_data = [sample_idx[:-1]]  # 'if you want yo'
y_data = [sample_idx[1:]]   # 'f you want you'

In [58]:
# 하이퍼 파라미터 
num_classes = len(idx2char)         # 10
dic_size = len(char2idx)            # 10
rnn_hidden_size = len(char2idx)     # 10
sequense_length = len(sample) - 1   # 14
batch_size = 1
learning_rate = 0.1

In [59]:
x_one_hot = tf.one_hot(x_data, num_classes) # (1, 14, 10)
y_one_hot = tf.one_hot(y_data, num_classes) # (1, 14, 10)

In [ ]:
model = keras.Sequential();
model.add(keras.layers.LSTM(units=num_classes, 
                            input_shape=(x_one_hot.shape[1], x_one_hot.shape[2]), 
                            return_sequences=True))
model.add(keras.layers.TimeDistributed(keras.layers.Dense(units=num_classes, activation='softmax')))
model.summary()

model.compile(loss='categorical_crossentropy', 
              optimizer=keras.optimizers.Adam(learning_rate=learning_rate),
              metrics=['accuracy'])

model.fit(x_one_hot, y_one_hot, epochs=50)

In [64]:
predictions = model.predict(x_one_hot)

for i, prediction in enumerate(predictions):
    result_str = [idx2char[c] for c in np.argmax(prediction, axis=1)]
    print("Prediction str: ", ''.join(result_str))

Prediction str:  f you want you


## 긴 문자열 사용하기

In [70]:
sentence = ("if you want to build a ship, don't drum up people together to "
            "collect wood and don't assign them tasks and work, but rather "
            "teach them to long for the endless immensity of the sea.")

char_set = list(set(sentence))                     # 인덱스를 넣으면 캐릭터를 뱉는다.
char_dic  = {c: i for i,c in enumerate(char_set)}   # 캐릭터를 넣으면 인덱스를 뱉는다.

In [84]:
data_dim = len(char_set)    # 25
hidden_size = len(char_set) # 25
num_classes = len(char_set) # 25
sequence_length = 10  # Any arbitrary number
learning_rate = 0.1

25

In [96]:
dataX = []
dataY = []
for i in range(len(sentence) - sequence_length):
    x_str = sentence[i:i + sequence_length]
    y_str = sentence[i + 1: i + sequence_length + 1]
    # print(i, x_str, '->' , y_str)

    # 인덱스로 변경
    x = [char_dic[c] for c in x_str]
    y = [char_dic[c] for c in y_str]

    dataX.append(x)
    dataY.append(y)

batch_size = len(dataX)

In [98]:
X_one_hot = tf.one_hot(dataX, num_classes)  # (170, 10, 25)
Y_one_hot = tf.one_hot(dataY, num_classes)  

In [ ]:
model = keras.Sequential()

model.add(keras.layers.LSTM(units=num_classes, input_shape=(sequence_length, X_one_hot.shape[2]), return_sequences=True))
model.add(keras.layers.LSTM(units=num_classes, return_sequences=True))
model.add(keras.layers.TimeDistributed(keras.layers.Dense(units=num_classes, activation='softmax')))
model.summary()

model.compile(loss='categorical_crossentropy', 
              optimizer=keras.optimizers.Adam(learning_rate=learning_rate),
              metrics=['accuracy'])

model.fit(X_one_hot, Y_one_hot, epochs=100)

In [100]:
results = model.predict(X_one_hot)
for j, result in enumerate(results):
    index = np.argmax(result, axis=1)
    if j == 0:  # print all for the first result to make a sentence
        print(''.join([char_set[t] for t in index]), end='')
    else:
        print(char_set[index[-1]], end='')

g you want to build a ship, don't drum up people together to collect wood and don't assign them tasks and work, but rather teach them to long for the endless immensity of the sea.