# Logistic regression 구현

In [ ]:
import tensorflow as tf
import numpy as np

X = np.array([[1, 2],
            [2, 3],
            [3, 1],
            [4, 3],
            [5, 3],
            [6, 2]], dtype='float32')
Y = np.array([[0],[0],[0],[1],[1],[1]],dtype='float32')

W = tf.Variable(tf.random.normal([2, 1]), name='weight')
b = tf.Variable(tf.random.normal([1]), name='bias')

In [ ]:
# hypothesis

# hypothesis = tf.math.divide(1., 1. + tf.exp(tf.matmul(X, W) + b))
hypothesis = tf.sigmoid(tf.matmul(X, W) + b)
hypothesis

<tf.Tensor: shape=(6, 1), dtype=float32, numpy=
array([[0.16532174],
       [0.1528    ],
       [0.30247962],
       [0.22221237],
       [0.26447725],
       [0.3848092 ]], dtype=float32)>

In [ ]:
# cost function
cost = -tf.reduce_mean(Y * tf.math.log(hypothesis) + 
                       (1 - Y) * tf.math.log(1 - hypothesis))
cost

<tf.Tensor: shape=(), dtype=float32, numpy=0.74931335>

In [ ]:
# train

learning_rate = 0.01
for i in range(5000):
    with tf.GradientTape() as tape:
        hypothesis = tf.sigmoid(tf.matmul(X, W) + b)
        cost = -tf.reduce_mean(Y * tf.math.log(hypothesis) \
                + (1 - Y) * tf.math.log(1 - hypothesis))

    W_grad, b_grad = tape.gradient(cost, [W, b])
    
    W.assign_sub(learning_rate * W_grad)
    b.assign_sub(learning_rate * b_grad)

In [ ]:
# prediction 

predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32)
predicted

<tf.Tensor: shape=(6, 1), dtype=float32, numpy=
array([[0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.]], dtype=float32)>

In [ ]:
# accuracy

accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))
accuracy

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

## 전체 코드

In [ ]:
import tensorflow as tf
import numpy as np

X = np.array([[1, 2],[2, 3],[3, 1],[4, 3],[5, 3],[6, 2]], dtype='float32')
Y = np.array([[0],[0],[0],[1],[1],[1]],dtype='float32')

W = tf.Variable(tf.random.normal([2, 1]), name='weight')
b = tf.Variable(tf.random.normal([1]), name='bias')

epochs = 10001
learning_rate = 0.01

for step in range(epochs):
    with tf.GradientTape() as tape:
        hypothesis = tf.sigmoid(tf.matmul(X, W) + b)
        cost = -tf.reduce_mean(Y * tf.math.log(hypothesis) \
                + (1 - Y) * tf.math.log(1 - hypothesis))

    W_grad, b_grad = tape.gradient(cost, [W, b])
    
    W.assign_sub(learning_rate * W_grad)
    b.assign_sub(learning_rate * b_grad)

    if step % 500 == 0:
        print(step, cost)

predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

print('\n',hypothesis,'\n\n', predicted,'\n\n',accuracy)

0 tf.Tensor(4.419512, shape=(), dtype=float32)
500 tf.Tensor(0.65555054, shape=(), dtype=float32)
1000 tf.Tensor(0.4573966, shape=(), dtype=float32)
1500 tf.Tensor(0.40397248, shape=(), dtype=float32)
2000 tf.Tensor(0.3694824, shape=(), dtype=float32)
2500 tf.Tensor(0.34111276, shape=(), dtype=float32)
3000 tf.Tensor(0.31645992, shape=(), dtype=float32)
3500 tf.Tensor(0.2947326, shape=(), dtype=float32)
4000 tf.Tensor(0.27548066, shape=(), dtype=float32)
4500 tf.Tensor(0.25835845, shape=(), dtype=float32)
5000 tf.Tensor(0.24307586, shape=(), dtype=float32)
5500 tf.Tensor(0.2293847, shape=(), dtype=float32)
6000 tf.Tensor(0.2170728, shape=(), dtype=float32)
6500 tf.Tensor(0.20595926, shape=(), dtype=float32)
7000 tf.Tensor(0.19588993, shape=(), dtype=float32)
7500 tf.Tensor(0.18673348, shape=(), dtype=float32)
8000 tf.Tensor(0.17837818, shape=(), dtype=float32)
8500 tf.Tensor(0.17072807, shape=(), dtype=float32)
9000 tf.Tensor(0.16370144, shape=(), dtype=float32)
9500 tf.Tensor(0.157227

## 모델을 사용

### 1. 데이터로드

In [ ]:
import tensorflow as tf

x_data = [[1, 2],[2, 3],[3, 1],[4, 3],[5, 3],[6, 2]]
y_data = [[0],[0],[0],[1],[1],[1]]

### 2. 모델 객체 생성, 레이어 추가

In [ ]:
tf.model = tf.keras.Sequential()
tf.model.add(tf.keras.layers.Dense(units=1, input_dim=2, activation='sigmoid'))   # 인풋 아웃풋 크기 지정
tf.model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_2 (Dense)             (None, 1)                 3         
                                                                 
Total params: 3
Trainable params: 3
Non-trainable params: 0
_________________________________________________________________


### 3. 모델 컴파일

In [ ]:
# loss function, optimizer, metrics 지정

# loss는 이진 분류 문제이기 때문에 crossentropy 지정
# optimizer는 Gradient descent, learning rate은 0.01
# 성능 측정은 accuracy다.

tf.model.compile(loss='binary_crossentropy',   
                 optimizer=tf.keras.optimizers.SGD(lr=0.01), 
                 metrics=['accuracy'])
tf.model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_1 (Dense)             (None, 1)                 3         
                                                                 
 activation_1 (Activation)   (None, 1)                 0         
                                                                 
Total params: 3
Trainable params: 3
Non-trainable params: 0
_________________________________________________________________


/usr/local/lib/python3.7/dist-packages/keras/optimizer_v2/gradient_descent.py:102: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(SGD, self).__init__(name, **kwargs)


### 4. 훈련 및 성능 확인

In [ ]:
history = tf.model.fit(x_data, y_data, epochs=5000)
print("Accuracy: ", history.history['accuracy'][-1])

### 전체 코드

In [ ]:
# Lab 5 Logistic Regression Classifier
import tensorflow as tf

x_data = [[1, 2],[2, 3],[3, 1],[4, 3],[5, 3],[6, 2]]
y_data = [[0],[0],[0],[1],[1],[1]]

tf.model = tf.keras.Sequential()
tf.model.add(tf.keras.layers.Dense(units=1, input_dim=2))
tf.model.add(tf.keras.layers.Activation('sigmoid'))

''' 
better result with loss function == 'binary_crossentropy', try 'mse' for yourself
adding accuracy metric to get accuracy report during training
'''
tf.model.compile(loss='binary_crossentropy', optimizer=tf.keras.optimizers.SGD(lr=0.01), metrics=['accuracy'])
tf.model.summary()

history = tf.model.fit(x_data, y_data, epochs=10000)

# Accuracy report
print("Accuracy: ", history.history['accuracy'][-1])

# 당뇨병 데이터 사용하기

## 모델 사용하기

In [ ]:
import pandas as pd

data = pd.read_csv('https://raw.githubusercontent.com/hunkim/DeepLearningZeroToAll/master/data-03-diabetes.csv',header=None)
data.head()

,0,1,2,3,4,5,6,7,8
0,-0.294118,0.487437,0.180328,-0.292929,0.000000,0.001490,-0.531170,-0.033333,0
1,-0.882353,-0.145729,0.081967,-0.414141,0.000000,-0.207153,-0.766866,-0.666667,1
2,-0.058824,0.839196,0.049180,0.000000,0.000000,-0.305514,-0.492741,-0.633333,0
3,-0.882353,-0.105528,0.081967,-0.535354,-0.777778,-0.162444,-0.923997,0.000000,1
4,0.000000,0.376884,-0.344262,-0.292929,-0.602837,0.284650,0.887276,-0.600000,0


In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 759 entries, 0 to 758
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       759 non-null    float64
 1   1       759 non-null    float64
 2   2       759 non-null    float64
 3   3       759 non-null    float64
 4   4       759 non-null    float64
 5   5       759 non-null    float64
 6   6       759 non-null    float64
 7   7       759 non-null    float64
 8   8       759 non-null    int64  
dtypes: float64(8), int64(1)
memory usage: 53.5 KB


In [ ]:
import numpy as np
import tensorflow as tf

xy = np.loadtxt('https://raw.githubusercontent.com/hunkim/DeepLearningZeroToAll/master/data-03-diabetes.csv',delimiter=',', dtype=np.float32)
x_data = xy[:, :-1]
y_data = xy[:, -1]

8

In [ ]:
# 1. 모델 객체 생성 및 레이어 추가
tf.model = tf.keras.Sequential()
tf.model.add(tf.keras.layers.Dense(units=1,input_dim=x_data.shape[1], activation='sigmoid'))

# 2. 모델 컴파일 (loss, optimizer, metrics 지정)
tf.model.compile(
    loss='binary_crossentropy', 
    optimizer=tf.keras.optimizers.SGD(lr=0.01), 
    metrics=['accuracy']
)
tf.model.summary()

# 3. 훈련
history = tf.model.fit(x_data, y_data, epochs=500)

In [ ]:
# accuracy
print(f"Accuracy: {history.history['accuracy'][-1]}")

# predict a single data point
y_predict = tf.model.predict([[0.176471, 0.155779, 0, 0, 0, 0.052161, -0.952178, -0.733333]])
print(f"Predict: {y_predict}")

# evaluating model
evaluate = tf.model.evaluate(x_data, y_data)
print((f"loss: {evaluate[0]}, Accuracy: {evaluate[1]}"))

Accuracy: 0.7747035622596741
Predict: [[0.5837849]]
24/24 [==============================] - 1s 5ms/step - loss: 0.4772 - accuracy: 0.7747
loss: 0.47716569900512695, Accuracy: 0.7747035622596741


## 모델 사용하지 않고 직접 구현하기

In [67]:
import numpy as np
import tensorflow as tf

xy = np.loadtxt('https://raw.githubusercontent.com/hunkim/DeepLearningZeroToAll/master/data-03-diabetes.csv',delimiter=',', dtype=np.float32)
X = xy[:, :-1]
Y = xy[:, -1]

In [68]:
# W, b 선언

W = tf.Variable(tf.random.normal([X.shape[1], 1]), name='weight')
b = tf.Variable(tf.random.normal([1]), name='bias')

In [70]:
epochs = 5001
learning_rate = 0.01
for step in range(epochs):
    with tf.GradientTape() as tape:
        hypothesis = tf.sigmoid(tf.matmul(X, W) + b)
        cost = -tf.reduce_mean(Y * tf.math.log(hypothesis) + (1 - Y) * tf.math.log(1-hypothesis))
    W_grad, b_grad = tape.gradient(cost, [W, b])
    W.assign_sub(learning_rate * W_grad)
    b.assign_sub(learning_rate * b_grad)
    if step % 250 == 0:
        print(step, cost.numpy())

0 0.734928
250 0.7233878
500 0.7134445
750 0.704891
1000 0.6975471
1250 0.691249
1500 0.6858501
1750 0.68121976
2000 0.6772442
2250 0.67382455
2500 0.6708763
2750 0.66832703
3000 0.6661156
3250 0.6641906
3500 0.6625082
3750 0.661032
4000 0.6597316
4250 0.6585811
4500 0.657559
4750 0.6566473
5000 0.6558307


In [83]:
predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

print(f"Hypothesis: {hypothesis[:5]}, \n\n predicted: {predicted[:5]}, \n\n accuracy: {accuracy}")

Hypothesis: [[0.6623645 ]
 [0.6510827 ]
 [0.52221984]
 [0.7674545 ]
 [0.7526581 ]], 

 predicted: [[1.]
 [1.]
 [1.]
 [1.]
 [1.]], 

 accuracy: 0.6494468450546265


In [118]:
a = tf.Variable([[0.176471, 0.155779, 0, 0, 0, 0.052161, -0.952178, -0.733333]], dtype=tf.float32)
hypothesis = tf.sigmoid(tf.matmul(a, W) + b)
hypothesis
# predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32)
# predicted

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[0.613649]], dtype=float32)>