In [1]:
import tensorflow as tf
import numpy as np

X = [[73., 80., 75.],
    [93., 88., 93.],
    [89., 91., 90.],
    [96., 98., 100.],
    [73., 66., 70.]]
Y = [[152.],
    [185.],
    [180.],
    [196.],
    [142.]]

In [ ]:
W = tf.Variable(tf.random.normal([3,1]))
b = tf.Variable(tf.random.normal([1]))

learning_rate = 0.000001

def hypothesis(X):
    return tf.matmul(X, W) + b

n_epochs = 2001
for i in range(n_epochs):
    with tf.GradientTape() as tape:
        cost = tf.reduce_mean((tf.square(hypothesis(X) - Y)))

    W_grad, b_grad = tape.gradient(cost, [W, b])

    W.assign_sub(learning_rate * W_grad)
    b.assign_sub(learning_rate * b_grad)

    if i % 100 == 0:
        print(f'{i}   {cost.numpy()}')

0   7671.796875
100   4.152138710021973
200   3.1916003227233887
300   3.175100803375244
400   3.1588332653045654
500   3.1426050662994385
600   3.12650990486145
700   3.1104955673217773
800   3.0945358276367188
900   3.0787036418914795
1000   3.062938928604126
1100   3.0472958087921143
1200   3.0316855907440186
1300   3.0161898136138916
1400   3.0007615089416504
1500   2.9854302406311035
1600   2.970165729522705
1700   2.9549734592437744
1800   2.939884662628174
1900   2.9248480796813965
2000   2.9099507331848145


# ML lab 04-2: TensorFlow로 파일에서 데이타 읽어오기 (new)

In [5]:
tf.random.set_seed(777)
xy = np.loadtxt('https://raw.githubusercontent.com/hunkim/DeepLearningZeroToAll/master/data-01-test-score.csv',
                delimiter=',',dtype=np.float32)
X = xy[:, :-1]
Y = xy[:, [-1]]

# print(X.shape, Y.shape)

W = tf.Variable(tf.random.normal([3,1]), name='weight')
b = tf.Variable(tf.random.normal([1]), name='bias')

learning_rate = 0.00001

for i in range(2001):
    with tf.GradientTape() as tape:
        hypothesis = tf.matmul(X, W) + b
        cost = tf.reduce_mean(tf.square(hypothesis - Y))

    W_grad, b_grad = tape.gradient(cost, [W, b])

    W.assign_sub(learning_rate * W_grad)
    b.assign_sub(learning_rate * b_grad)

    if i % 100 == 0:
        print(f'{i} {cost.numpy():.5f}')

0 6115.09814
100 26.48511
200 25.05040
300 23.72239
400 22.49270
500 21.35378
600 20.29849
700 19.32040
800 18.41356
900 17.57247
1000 16.79213
1100 16.06787
1200 15.39543
1300 14.77087
1400 14.19056
1500 13.65123
1600 13.14972
1700 12.68326
1800 12.24921
1900 11.84518
2000 11.46895


In [6]:
# predict
X = np.array([[100, 70, 101]], dtype='float32')
print(tf.matmul(X, W) + b)

X = np.array([[60, 70, 110], [90, 100, 80]], dtype='float32')
print(tf.matmul(X, W) + b)

tf.Tensor([[187.75224]], shape=(1, 1), dtype=float32)
tf.Tensor(
[[162.46992]
 [180.48015]], shape=(2, 1), dtype=float32)


In [ ]:
# Lab 4 Multi-variable linear regression
import tensorflow as tf
import numpy as np

xy = np.loadtxt('https://raw.githubusercontent.com/hunkim/DeepLearningZeroToAll/master/data-01-test-score.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

# Make sure the shape and data are OK
print(x_data, "\nx_data shape:", x_data.shape)
print(y_data, "\ny_data shape:", y_data.shape)

tf.model = tf.keras.Sequential()
# activation function doesn't have to be added as a separate layer. Add it as an argument of Dense() layer
tf.model.add(tf.keras.layers.Dense(units=1, input_dim=3, activation='linear'))
# tf.model.add(tf.keras.layers.Activation('linear'))
tf.model.summary()

tf.model.compile(loss='mse', optimizer=tf.keras.optimizers.SGD(lr=1e-5))
history = tf.model.fit(x_data, y_data, epochs=2000)

# Ask my score
print("Your score will be ", tf.model.predict([[100, 70, 101]]))
print("Other scores will be ", tf.model.predict([[60, 70, 110], [90, 100, 80]]))

[[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]] 
x_data shape: (25, 3)
[[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]] 
y_data shape: (25, 1)
Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 1)                 4         
                                                                 
Total params: 4
Tr

/usr/local/lib/python3.7/dist-packages/keras/optimizer_v2/gradient_descent.py:102: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(SGD, self).__init__(name, **kwargs)


1/1 [==============================] - 0s 410ms/step - loss: 16837.2520
Epoch 2/2000
1/1 [==============================] - 0s 9ms/step - loss: 6254.5610
Epoch 3/2000
1/1 [==============================] - 0s 8ms/step - loss: 2341.8286
Epoch 4/2000
1/1 [==============================] - 0s 7ms/step - loss: 895.1622
Epoch 5/2000
1/1 [==============================] - 0s 10ms/step - loss: 360.2693
Epoch 6/2000
1/1 [==============================] - 0s 8ms/step - loss: 162.4847
Epoch 7/2000
1/1 [==============================] - 0s 11ms/step - loss: 89.3378
Epoch 8/2000
1/1 [==============================] - 0s 4ms/step - loss: 62.2734
Epoch 9/2000
1/1 [==============================] - 0s 5ms/step - loss: 52.2467
Epoch 10/2000
1/1 [==============================] - 0s 5ms/step - loss: 48.5195
Epoch 11/2000
1/1 [==============================] - 0s 4ms/step - loss: 47.1214
Epoch 12/2000
1/1 [==============================] - 0s 5ms/step - loss: 46.5844
Epoch 13/2000
1/1 [=================