# 다중 분류모델 구현 (softmax)

In [ ]:
import tensorflow as tf
import numpy as np

In [ ]:
x_raw = [[1, 2, 1, 1],
          [2, 1, 3, 2],
          [3, 1, 3, 4],
          [4, 1, 5, 5],
          [1, 7, 5, 5],
          [1, 2, 5, 6],
          [1, 6, 6, 6],
          [1, 7, 7, 7]]
y_raw = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

X = tf.Variable(x_raw, dtype=tf.float32)
Y = tf.Variable(y_raw, dtype=tf.float32)

X.shape, Y.shape

(TensorShape([8, 4]), TensorShape([8, 3]))

## W, b 선언

In [ ]:
tf.random.set_seed(1)
W = tf.Variable(tf.random.normal([X.shape[1], Y.shape[1]]))
b = tf.Variable(tf.random.normal([Y.shape[1]]))

## softmax사용

In [ ]:
hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)
hypothesis

<tf.Tensor: shape=(8, 3), dtype=float32, numpy=
array([[2.8565836e-01, 3.7394714e-01, 3.4039453e-01],
       [5.3686995e-02, 8.5996407e-01, 8.6349003e-02],
       [3.5553421e-03, 9.7092170e-01, 2.5522944e-02],
       [4.2082410e-04, 9.9589503e-01, 3.6841526e-03],
       [8.6085874e-01, 9.1479063e-02, 4.7662273e-02],
       [5.7206035e-01, 3.7504575e-01, 5.2893911e-02],
       [8.6537063e-01, 1.0668026e-01, 2.7949080e-02],
       [9.1987050e-01, 6.5981843e-02, 1.4147675e-02]], dtype=float32)>

## 손실함수 정의

In [ ]:
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.math.log(hypothesis), axis=1))
cost.numpy()

1.3499714

## Gradient discent 적용

In [ ]:
learning_rate = 0.001
for i in range(2001):
    with tf.GradientTape() as tape:
        hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)
        cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.math.log(hypothesis), axis=1))

    W_grad, b_grad = tape.gradient(cost, [W, b])

    W.assign_sub(learning_rate * W_grad)
    b.assign_sub(learning_rate * b_grad)
    if i % 100 == 0:
        print(hypothesis, '\n\n',cost)

## 전체 코드

In [ ]:
import tensorflow as tf
import numpy as np

x_raw = [[1, 2, 1, 1],
          [2, 1, 3, 2],
          [3, 1, 3, 4],
          [4, 1, 5, 5],
          [1, 7, 5, 5],
          [1, 2, 5, 6],
          [1, 6, 6, 6],
          [1, 7, 7, 7]]
y_raw = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

X = tf.Variable(x_raw, dtype=tf.float32)
Y = tf.Variable(y_raw, dtype=tf.float32)

tf.random.set_seed(1)
W = tf.Variable(tf.random.normal([X.shape[1], Y.shape[1]]))
b = tf.Variable(tf.random.normal([Y.shape[1]]))

learning_rate = 0.1
for i in range(3001):
    with tf.GradientTape() as tape:
        hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)
        cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.math.log(hypothesis), axis=1))

    W_grad, b_grad = tape.gradient(cost, [W, b])

    W.assign_sub(learning_rate * W_grad)
    b.assign_sub(learning_rate * b_grad)
    if i % 100 == 0:
        print(hypothesis, '\n\n',cost)

tf.Tensor(
[[2.8565836e-01 3.7394714e-01 3.4039453e-01]
 [5.3686995e-02 8.5996407e-01 8.6349003e-02]
 [3.5553421e-03 9.7092170e-01 2.5522944e-02]
 [4.2082410e-04 9.9589503e-01 3.6841526e-03]
 [8.6085874e-01 9.1479063e-02 4.7662273e-02]
 [5.7206035e-01 3.7504575e-01 5.2893911e-02]
 [8.6537063e-01 1.0668026e-01 2.7949080e-02]
 [9.1987050e-01 6.5981843e-02 1.4147675e-02]], shape=(8, 3), dtype=float32) 

 tf.Tensor(1.3499714, shape=(), dtype=float32)
tf.Tensor(
[[8.1229195e-02 7.8883618e-02 8.3988714e-01]
 [3.0000174e-02 1.8852948e-01 7.8147030e-01]
 [1.4909967e-03 2.7855271e-01 7.1995628e-01]
 [5.2492536e-04 4.3631312e-01 5.6316197e-01]
 [8.9322984e-01 6.3970298e-02 4.2799860e-02]
 [5.3775257e-01 4.1783375e-01 4.4413675e-02]
 [9.0637761e-01 7.8588501e-02 1.5033923e-02]
 [9.4868881e-01 4.7074590e-02 4.2366562e-03]], shape=(8, 3), dtype=float32) 

 tf.Tensor(0.669001, shape=(), dtype=float32)
tf.Tensor(
[[2.92026456e-02 4.41671088e-02 9.26630318e-01]
 [2.00987011e-02 1.52381569e-01 8.275197

In [44]:
# 예측
# onehot 인코딩 적용
prediction = tf.nn.softmax(tf.matmul(np.array([[1, 11, 7, 9]], dtype='float32'), W) + b)
prediction.numpy(), np.argmax(prediction, axis=1)

(array([[4.7394601e-04, 9.9952316e-01, 2.8894171e-06]], dtype=float32),
 array([1]))

# 모델을 사용해서 구현

In [ ]:
import tensorflow as tf
import numpy as np

x_raw = [[1, 2, 1, 1],
          [2, 1, 3, 2],
          [3, 1, 3, 4],
          [4, 1, 5, 5],
          [1, 7, 5, 5],
          [1, 2, 5, 6],
          [1, 6, 6, 6],
          [1, 7, 7, 7]]
y_raw = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

# 데이터를 넘파이 어레이 & float으로 변환
x_data = np.array(x_raw, dtype=np.float32)    
y_data = np.array(y_raw, dtype=np.float32)

nb_classes = y_data.shape[1]  # 클래스의 개수 3
input_shape = x_data.shape[1] # feature의 개수 4

## 2. 모델 객체 생성

In [ ]:
tf.model = tf.keras.Sequential()
tf.model.add(tf.keras.layers.Dense(input_dim = input_shape, 
                                   units=nb_classes, 
                                   use_bias=True, 
                                   activation='softmax'))

## 3. 모델 컴파일

In [ ]:
tf.model.compile(loss='categorical_crossentropy', 
                 optimizer=tf.keras.optimizers.SGD(lr=0.1), 
                 metrics=['accuracy'])
tf.model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 3)                 15        
                                                                 
Total params: 15
Trainable params: 15
Non-trainable params: 0
_________________________________________________________________


/usr/local/lib/python3.7/dist-packages/keras/optimizer_v2/gradient_descent.py:102: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(SGD, self).__init__(name, **kwargs)


## 4. 훈련

In [ ]:
history = tf.model.fit(x_data, y_data, epochs=2000)

Epoch 1/2000
1/1 [==============================] - 1s 1s/step - loss: 4.0626 - accuracy: 0.3750
Epoch 2/2000
1/1 [==============================] - 0s 13ms/step - loss: 1.6480 - accuracy: 0.3750
Epoch 3/2000
1/1 [==============================] - 0s 13ms/step - loss: 1.4947 - accuracy: 0.2500
Epoch 4/2000
1/1 [==============================] - 0s 12ms/step - loss: 1.5243 - accuracy: 0.3750
Epoch 5/2000
1/1 [==============================] - 0s 13ms/step - loss: 1.3116 - accuracy: 0.3750
Epoch 6/2000
1/1 [==============================] - 0s 18ms/step - loss: 1.2812 - accuracy: 0.3750
Epoch 7/2000
1/1 [==============================] - 0s 20ms/step - loss: 1.2644 - accuracy: 0.3750
Epoch 8/2000
1/1 [==============================] - 0s 26ms/step - loss: 1.2255 - accuracy: 0.3750
Epoch 9/2000
1/1 [==============================] - 0s 17ms/step - loss: 1.2301 - accuracy: 0.5000
Epoch 10/2000
1/1 [==============================] - 0s 13ms/step - loss: 1.1619 - accuracy: 0.3750
Epoch 11/20

## 모델 테스트

In [ ]:
a = tf.model.predict(np.array([[1, 11, 7, 9]]))
print(a, tf.keras.backend.eval(tf.argmax(a, axis=1)))

[[1.2240880e-02 9.8774844e-01 1.0543893e-05]] [1]


In [ ]:
c = tf.model.predict(np.array([[1, 1, 0, 1]]))
# c_onehot = tf.model.predict_classes(np.array([[1, 1, 0, 1]]))
print(a, np.argmax(a, axis=1))

[[1.2240880e-02 9.8774844e-01 1.0543893e-05]] [1]
