# 텐서 다루기

## 1차원

In [25]:
import numpy as np
import tensorflow as tf
t = np.array(range(7), np.float32)
t

array([0., 1., 2., 3., 4., 5., 6.], dtype=float32)

In [26]:
t.reshape([-1, 1])

array([[0.],
       [1.],
       [2.],
       [3.],
       [4.],
       [5.],
       [6.]], dtype=float32)

In [27]:
t.astype('int32')

array([0, 1, 2, 3, 4, 5, 6], dtype=int32)

## 2차원

In [16]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
t

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])

In [18]:
t.reshape([-1, 6])

array([[ 1.,  2.,  3.,  4.,  5.,  6.],
       [ 7.,  8.,  9., 10., 11., 12.]])

In [17]:
tf.reshape(t, [-1, 6])

<tf.Tensor: shape=(2, 6), dtype=float64, numpy=
array([[ 1.,  2.,  3.,  4.,  5.,  6.],
       [ 7.,  8.,  9., 10., 11., 12.]])>